In [1]:
import pandas as pd
from Bio.SeqUtils import gc_fraction
import numpy as np

In [2]:
###Define reverseComplement sequence###

def reverseComplement(DNA) : 
    '''
    Create the reverse complement of a DNA string
    
    Input : A DNA string 
    Output : The reverse complement of the DNA string given
    '''
    
    complements = DNA.maketrans('acgtACGT','tgcaTGCA')
    complements_DNA = DNA.translate(complements)
    DNA_rc = complements_DNA[::-1]
    
    return DNA_rc

###Run this line in the terminal :

python generate_barcodes.py 12 /Users/alexandre/Desktop/all_possible_barcode_12bp.txt

###This will generate all possible 12bp DNA combinaison
###Make sure to bee in the directory where generate_barcodes.py script is located

In [76]:
###Load full list of barcodes into dataframe###

bc_lst = pd.read_csv('/Users/alexandre/Desktop/all_possible_barcode_12bp.txt', sep=',', header=None, names=['seq'])
bc_lst.head()

            seq
0  AAAAAAAAAAAA
1  AAAAAAAAAAAC
2  AAAAAAAAAAAG
3  AAAAAAAAAAAT
4  AAAAAAAAAACA

In [77]:
###Randomize the dataframe with the barcodes###

bc_lst = bc_lst.sample(frac=1).reset_index(drop=True)

In [82]:
###Save the randomize list of barcode to use in the validate_barcode.py script###

np.savetxt('/Users/alexandre/Desktop/random_file_all_barcode.txt', bc_lst.values, fmt='%s')

###Run this line in the terminal :

python validate_barcodes.py /Users/alexandre/Desktop/random_file_all_barcode.txt /Users/alexandre/Desktop/30000_barcode_3mismatch_gc_04_06.txt 30000 12 0.4 0.6 3

###This will select all possible 12bp DNA combinaison that have a GC content between 40 and 60%, with 3 base pairs difference between them.
###Make sure to bee in the directory where validate_barcodes.py script is located

In [3]:
###Load validated barcode in dataframe##

df_bc = pd.read_csv('/Users/alexandre/Desktop/30000_barcode_3mismatch_gc_04_06.txt', sep=',', header=None, names=['seq'])
df_bc.head()

            seq
0  TAGCCTCGCAGA
1  ACACGTACGGTA
2  TCGGTTAACATC
3  TCGTACGCAACC
4  ACATCCGAGCTA

In [4]:
###Identify barcode with a BsaI site already in and remove them###

df_bc['BsaI_f'] = 0
df_bc['BsaI_r'] = 0

for i in df_bc.index:
    
    if 'GGTCTC' in df_bc.loc[i]['seq']:
        
        df_bc.at[i, 'BsaI_f'] = 1
        
    if 'GGTCTC' in reverseComplement(df_bc.loc[i]['seq']):
        
        df_bc.at[i, 'BsaI_r'] = 1

print(len(df_bc))

df_bc = df_bc[(df_bc['BsaI_f'] == 0 ) & (df_bc['BsaI_r'] == 0)]

print(len(df_bc))

30000
29888

In [5]:
###Identify barcode with the last 4-5 base of BsaI to start their sequence##

df_bc['BsaI_f_4'] = 0
df_bc['BsaI_f_5'] = 0

for i in df_bc.index:
    
    hld_seq = df_bc.loc[i]['seq']
    
    if 'TCTC' in hld_seq[:4]:
        
        df_bc.at[i, 'BsaI_f_4'] = 1
        
    if 'GTCTC' in hld_seq[:5]:
        
        df_bc.at[i, 'BsaI_f_5'] = 1

print(len(df_bc))

df_bc = df_bc[(df_bc['BsaI_f_4'] == 0 ) & (df_bc['BsaI_f_5'] == 0)]

print(len(df_bc))

29888
29691

In [6]:
###Identify barcode with the last 4-5 base of BsaI to finish their sequence##

df_bc['BsaI_f_end4'] = 0
df_bc['BsaI_f_end5'] = 0

for i in df_bc.index:
    
    hld_seq = df_bc.loc[i]['seq']
    
    if 'GGTC' in hld_seq[-4:]:
        
        df_bc.at[i, 'BsaI_f_end4'] = 1
        
    if 'GGTCT' in hld_seq[-5:]:
        
        df_bc.at[i, 'BsaI_f_end5'] = 1

print(len(df_bc))

df_bc = df_bc[(df_bc['BsaI_f_end4'] == 0 ) & (df_bc['BsaI_f_end5'] == 0)]

print(len(df_bc))

29691
29540

In [7]:
###Identify barcode with the last 4-5 base of BsaI to start their sequence in reverse complement##

df_bc['BsaI_r_4'] = 0
df_bc['BsaI_r_5'] = 0

for i in df_bc.index:
    
    hld_seq = reverseComplement(df_bc.loc[i]['seq'])
    
    if 'TCTC' in hld_seq[:4]:
        
        df_bc.at[i, 'BsaI_r_4'] = 1
        
    if 'GTCTC' in hld_seq[:5]:
        
        df_bc.at[i, 'BsaI_r_5'] = 1

print(len(df_bc))

df_bc = df_bc[(df_bc['BsaI_r_4'] == 0 ) & (df_bc['BsaI_r_5'] == 0)]

print(len(df_bc))

29540
29337

In [8]:
###Identify barcode with the last 4-5 base of BsaI to finish their sequence in reverse complement##

df_bc['BsaI_r_end4'] = 0
df_bc['BsaI_r_end5'] = 0

for i in df_bc.index:
    
    hld_seq = reverseComplement(df_bc.loc[i]['seq'])
    
    if 'GGTC' in hld_seq[-4:]:
        
        df_bc.at[i, 'BsaI_r_end4'] = 1
        
    if 'GGTCT' in hld_seq[-5:]:
        
        df_bc.at[i, 'BsaI_r_end5'] = 1

print(len(df_bc))

df_bc = df_bc[(df_bc['BsaI_r_end4'] == 0 ) & (df_bc['BsaI_r_end5'] == 0)]

print(len(df_bc))

29337
29214

In [9]:
###Identify barcode with the last 1-2-3 base of BsaI to finish their sequence##

df_bc['BsaI_f_3end'] = 0
df_bc['BsaI_r_3end'] = 0
df_bc['BsaI_f_2end'] = 0
df_bc['BsaI_r_2end'] = 0
df_bc['BsaI_f_1end'] = 0
df_bc['BsaI_r_1end'] = 0

for i in df_bc.index:
    
    hld_seq = df_bc.loc[i]['seq']
    
    if 'GGT' in hld_seq[-3:]:
        
        df_bc.at[i, 'BsaI_f_3end'] = 1
        
    if 'GGT' in reverseComplement(hld_seq[-3:]):
        
        df_bc.at[i, 'BsaI_r_3end'] = 1

    if 'GG' in hld_seq[-2:]:
        
        df_bc.at[i, 'BsaI_f_2end'] = 1
        
    if 'GG' in reverseComplement(hld_seq[-2:]):
        
        df_bc.at[i, 'BsaI_r_2end'] = 1
    
    #if 'G' in hld_seq[-1:]:
        
        #df_bc.at[i, 'BsaI_f_1end'] = 1
        
    #if 'G' in reverseComplement(hld_seq[-1:]):
        
        #df_bc.at[i, 'BsaI_r_1end'] = 1

In [10]:
###Identify barcode with the last 1-2-3 base of BsaI to start their sequence##

df_bc['BsaI_f_3start'] = 0
df_bc['BsaI_r_3start'] = 0
df_bc['BsaI_f_2start'] = 0
df_bc['BsaI_r_2start'] = 0
df_bc['BsaI_f_1start'] = 0
df_bc['BsaI_r_1start'] = 0

for i in df_bc.index:
    
    hld_seq = df_bc.loc[i]['seq']
    
    if 'CTC' in hld_seq[:3]:
        
        df_bc.at[i, 'BsaI_f_3start'] = 1
        
    if 'CTC' in reverseComplement(hld_seq[:3]):
        
        df_bc.at[i, 'BsaI_r_3start'] = 1

    if 'TC' in hld_seq[:2]:
        
        df_bc.at[i, 'BsaI_f_2start'] = 1
        
    if 'TC' in reverseComplement(hld_seq[:2]):
        
        df_bc.at[i, 'BsaI_r_2start'] = 1
    
    if 'C' in hld_seq[:1]:
        
        df_bc.at[i, 'BsaI_f_1start'] = 1
        
    if 'C' in reverseComplement(hld_seq[:1]):
        
        df_bc.at[i, 'BsaI_r_1start'] = 1

In [11]:
###Remove all barcode with possible base mathcing BsaI at the start or end###

print(len(df_bc))

for i in df_bc.columns[1:-2]:
    
    df_bc = df_bc[df_bc[i] == 0]
    print(len(df_bc))

29214
29214
29214
29214
29214
29214
29214
29214
29214
29214
29214
28760
28229
26731
25789
25789
25789
25309
24834
23154
21874

In [12]:
###Remove all barcode that start or end with two identical base###

df_bc['start_double'] = 0
df_bc['end_double'] = 0

print(len(df_bc))

for i in df_bc.index:
    
    if df_bc.loc[i]['seq'][0] == df_bc.loc[i]['seq'][1]:
        
        df_bc.at[i, 'start_double'] = 1
        
    if df_bc.loc[i]['seq'][10] == df_bc.loc[i]['seq'][11]:
        
        df_bc.at[i, 'end_double'] = 1
        
df_bc = df_bc[(df_bc['start_double'] == 0 ) & (df_bc['end_double'] == 0)]

print(len(df_bc))

21874
14797

In [13]:
###Select only barcode sequence to a new dataframe and reset indexes###

df_bc_end = df_bc[['seq']].copy()
df_bc_end.reset_index(drop=True, inplace=True)
df_bc_end

                seq
0      TAGCCTCGCAGA
1      ACACGTACGGTA
2      ACATCCGAGCTA
3      CAGAGTGGTACA
4      ACTCCAATCCTG
...             ...
14792  ACGTAAGCGTCG
14793  TAGCCGATTCTA
14794  TGGATACCACTG
14795  CATCGAGCACCA
14796  TGTACGAATCGT

[14797 rows x 1 columns]

In [14]:
###Calculate GC content of each barcode###

df_bc_end['GC_content'] = 0

for i in df_bc_end.index:
    
    df_bc_end.loc[i, 'GC_content'] = gc_fraction(df_bc_end.loc[i]['seq'])

In [15]:
###Separate bc based on GC content###

df_bc_50 = df_bc_end[df_bc_end['GC_content'] == 0.5]
df_bc_40 = df_bc_end[df_bc_end['GC_content'] < 0.5]
df_bc_60 = df_bc_end[df_bc_end['GC_content'] > 0.5]

df_bc_50.reset_index(drop=True, inplace=True)
df_bc_40.reset_index(drop=True, inplace=True)
df_bc_60.reset_index(drop=True, inplace=True)

In [21]:
len(df_bc_40)

4796

In [23]:
###Generate final dataframe with final barcode###

df_bc_opool = pd.DataFrame(columns=['seq', 'GC_content'])
df_bc_opool2 = pd.DataFrame(columns=['seq', 'GC_content'])

for i in range(0,5386,2):
    
    df_bc_opool.at[i, 'seq'] = 'NN' + df_bc_50.loc[i]['seq'] + 'NN' + df_bc_50.loc[i+1]['seq'] + 'NN'
    df_bc_opool.at[i, 'GC_content'] = gc_fraction(df_bc_opool.loc[i]['seq'])
    
for j in df_bc_60.index:
    
    df_bc_opool2.at[j, 'seq'] = 'NN' + df_bc_60.loc[j]['seq'] + 'NN' + df_bc_40.loc[j]['seq'] + 'NN'
    df_bc_opool2.at[j, 'GC_content'] = gc_fraction(df_bc_opool2.loc[j]['seq'])

In [24]:
###Join the two dataframe together##

frames = [df_bc_opool, df_bc_opool2]
df_final = pd.concat(frames)
df_final.reset_index(drop=True, inplace=True)

In [25]:
###Save to csv barcode list###

df_final.to_csv('/Users/alexandre/Desktop/barcode_pdr1_fin.csv', sep='\t')

In [26]:
###Calculate ratio of each position in the non-N barcode###

ratio_df = pd.DataFrame(0, columns=[2,3,4,5,6,7,8,9,10,11,12,13,16,17,18,19,20,21,22,23,24,25,26,27], index=['A', 'C', 'T', 'G'])

for i in df_final.index:
    
    hld_seq = df_final.loc[i]['seq']
    
    for j in ratio_df.columns:
        
        if 'A' == hld_seq[j]:
            
            ratio_df.at['A', j] +=1
        
        if 'C' == hld_seq[j]:
            
            ratio_df.at['C', j] +=1

        if 'T' == hld_seq[j]:
            
            ratio_df.at['T', j] +=1
    
        if 'G' == hld_seq[j]:
            
            ratio_df.at['G', j] +=1
            
ratio_df.loc['A_r'] = ratio_df.loc['A']/len(df_final)
ratio_df.loc['C_r'] = ratio_df.loc['C']/len(df_final)
ratio_df.loc['T_r'] = ratio_df.loc['T']/len(df_final)
ratio_df.loc['G_r'] = ratio_df.loc['G']/len(df_final)

In [28]:
ratio_df

,2,3,4,5,6,7,8,9,10,11,...,18,19,20,21,22,23,24,25,26,27
A,2003.000000,1288.000000,1668.000000,1623.000000,1635.000000,1637.000000,1633.000000,1601.000000,1665.000000,1652.000000,...,2134.000000,1977.000000,2008.000000,2053.000000,1982.000000,2021.000000,2000.000000,2029.000000,2014.000000,1986.000000
C,2308.000000,1708.000000,1883.000000,2089.000000,1993.000000,2028.000000,2031.000000,2039.000000,2054.000000,2087.000000,...,1520.000000,1631.000000,1672.000000,1611.000000,1658.000000,1629.000000,1655.000000,1695.000000,1724.000000,1641.000000
T,1267.000000,1839.000000,1650.000000,1581.000000,1649.000000,1663.000000,1614.000000,1633.000000,1600.000000,1692.000000,...,2047.000000,1993.000000,1983.000000,2009.000000,1975.000000,2038.000000,2036.000000,2044.000000,2012.000000,1918.000000
G,1729.000000,2472.000000,2106.000000,2014.000000,2030.000000,1979.000000,2029.000000,2034.000000,1988.000000,1876.000000,...,1606.000000,1706.000000,1644.000000,1634.000000,1692.000000,1619.000000,1616.000000,1539.000000,1557.000000,1762.000000
A_r,0.274121,0.176269,0.228274,0.222116,0.223758,0.224032,0.223484,0.219105,0.227864,0.226085,...,0.292049,0.270562,0.274805,0.280963,0.271247,0.276584,0.273710,0.277679,0.275626,0.271794
C_r,0.315862,0.233748,0.257698,0.285890,0.272752,0.277542,0.277953,0.279047,0.281100,0.285617,...,0.208020,0.223211,0.228822,0.220474,0.226906,0.222937,0.226495,0.231969,0.235938,0.224579
T_r,0.173395,0.251676,0.225811,0.216368,0.225674,0.227590,0.220884,0.223484,0.218968,0.231559,...,0.280142,0.272752,0.271384,0.274942,0.270289,0.278911,0.278637,0.279732,0.275352,0.262488
G_r,0.236622,0.338306,0.288217,0.275626,0.277816,0.270836,0.277679,0.278363,0.272068,0.256740,...,0.219789,0.233475,0.224990,0.223621,0.231559,0.221568,0.221158,0.210620,0.213083,0.241139